### ISSUE TITLE
Can run out of gas with too many taxpayers

### ISSUE THREAD

**Issue by mikedeshazer** [ItsNickBarry/ethereum-tax-dodgeball#1]
In https://github.com/ItsNickBarry/ethereum-tax-dodgeball/blob/master/contracts/ERC20HardFork.sol, if there are many tax payers the for loop in airdropping can run out of gas and the transaction will fail.
Perhaps setting a limit might work. If there's one set elsewhere, perhaps I missed it

**Comment by ItsNickBarry** [comment]
Thanks for reporting this.

It turns out that the `deployToken` function is more expensive per-address than the `airdrop` function (because it stores the list on-chain).  Because `deployToken` must be called before `airdrop`, it acts as an indirect limit.

I don't recall whether I made sure of that before or neglected it completely like any well-trained former IRS contractor.
